version: '3.8'
services:
 api:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        project: api
    ports:
      - 3333:3333
    restart: on-failure
    networks:
      - monorepo_net
    volumes:
      - ./:/usr/src/app

networks:
  monorepo_net:
    driver: bridge
