# Start a new stage from the official Nginx image
FROM nginx:alpine

# Copy the NGINX configuration file to the container
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/conf.d/

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Copy build artifacts from the previous stage
COPY ./dist/apps/frontend .

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]