version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        project: api
    ports:
      - "3333:3333"
    restart: on-failure
    networks:
      - monorepo_net

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.angular
      args:
        project: frontend
    ports:
      - "80:80" # Map container port 80 to host port 4200 4200:80
      - "443:443"
    networks:
      - monorepo_net
    depends_on:
      - api

networks:
  monorepo_net:
    driver: bridge
