version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.angular
      args:
        project: frontend
    ports:
      - 8000:80
    restart: on-failure
    networks:
      - monorepo_net
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.nest
      args:
        project: api
    ports:
      - 3333:3333
    restart: on-failure
    networks:
      - monorepo_net

networks:
  monorepo_net:
    driver: bridge
