version: "3.8"

services:
  gifster_api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        project: gifster_api
    ports:
      - "3333:3333"
    restart: on-failure
    networks:
      - monorepo_net

  gifster_frontend:
    build:
      context: ./
      dockerfile: Dockerfile.angular
      args:
        project: gifster_frontend
    ports:
      - "4200:80" # Map container port 80 to host port 4200
    networks:
      - monorepo_net
    depends_on:
      - gifster_api

networks:
  monorepo_net:
    driver: bridge
